### PR TITLE
Report enhancements

### PR DESCRIPTION
**Pull request by joshjohanning**
## 📝 Summary

> This pull request primarily focuses on two files: `.github/workflows/scorecard.yml` and `utils/reporting.js`. The changes in the `.github/workflows/scorecard.yml` file are minor, with a shift from double quotes to single quotes for string literals. The changes in the `utils/reporting.js` file are more substantial, with updates to the handling of workflow state data and the formatting of action URLs.
> 
> Changes to `.github/workflows/scorecard.yml`:
> 
> * Replaced double quotes with single quotes for string literals in various sections of the file. [[1]](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL15-R15) [[2]](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL34-R39) [[3]](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL61-R61) [[4]](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL70-R70)
> 
> Updates to `utils/reporting.js`:
> 
> * Added a fallback value of 'workflows not enabled in fork' for the `state` property in the `csvData` array and in other areas of the code. [[1]](diffhunk://#diff-0a97197dbd30f745e94eac587a185eab9ea8a4462a72fe0291810217a98c97e4L808-R817) [[2]](diffhunk://#diff-0a97197dbd30f745e94eac587a185eab9ea8a4462a72fe0291810217a98c97e4L880-R889) [[3]](diffhunk://#diff-0a97197dbd30f745e94eac587a185eab9ea8a4462a72fe0291810217a98c97e4L996-R1008)
> * Adjusted the handling of action URLs to account for local actions and actions from GitHub. This included splitting the action into different components, checking the URL, and formatting the final URL string.

### 1. [fix: .com workflow link in md report](https://github.com/stoe/action-reporting-cli/commit/17ec2116db0292027f109f3ef97d1229e9ed6636)

If you are pulling in workflows from .com, the url in the markdown was `https://undefined/org/repo..`.  

Like this:
```md
[.github/workflows/nuget-publish.yml](https://undefined/joshjohanning-test-gei-deleteme-2/Wolfringo-github-packages/blob/HEAD/.github/workflows/nuget-publish.yml)
```

This worked correctly as-is for GHES, though (and tested to work still after the change). 

### 2. [feat: support local actions in md report](https://github.com/stoe/action-reporting-cli/commit/86dd810202ee917b3fbcda3c5e55f1ba38add945)

Local actions showed up in the `CSV` and `JSON` reports, and I added some logic to bring in local actions to the `MD` report. It uses "`(local)`" as the version instead of the ref/tag that regular actions use. The local action links to the directory in the repo where the action is stored.

A local action will look like this in the report:

  > <li> [tspascoal/cobertura-action](https://github.com/tspascoal/cobertura-action) (`master`) </li>
  > <li>[actions/upload-artifact](https://github.com/actions/upload-artifact) (`v2`) </li> 
  > <li> <b>[./actions/provision-and-deploy](https://github.com/joshjohanning-org-test/MyShuttle/blob/HEAD/./actions/provision-and-deploy) (`local`)</b> </li>

image

### 3. [feat: note in state if workflows are disabled](https://github.com/stoe/action-reporting-cli/commit/5f089c8c06369392d1843f169b335792713946c3)

I was trying to figure out why some workflows were showing `undefined` for things like `name` and `state`. Originally I thought it was just because they had never been run before since the `created_at` and `updated_at` was also `undefined`, but I was still curious why the `name` property would return back `undefined`. 

I think the cause of this is that with forks, if you don't enable workflows to be run against the repository, the API returns empty

image

```
gh api /repos/joshjohanning-org-test/export-actions-usage-report/actions/workflows
{
  "total_count": 0,
  "workflows": []
}
```

I'm adding the `Workflows not enabled in fork` to the status field in this case.

image

### CODE REVIEW

**Comment by joshjohanning** [comment]
There _might have_ been a better way to do # 3 [feat: note in state if workflows are disabled](https://github.com/stoe/action-reporting-cli/commit/5f089c8c06369392d1843f169b335792713946c3) as opposed to setting it individually for each save csv, json, and markdown functions, but without refactoring the code I didn't see anywhere obvious since the workflow API returns empty and thus this [line never gets hit](https://github.com/stoe/action-reporting-cli/blob/5f089c8c06369392d1843f169b335792713946c3/utils/reporting.js#L316).

**Comment by stoe** [comment]
Thanks for the contributions @joshjohanning

**Comment by stoe** [comment]
> There _might have_ been a better way to do # 3 [feat: note in state if workflows are disabled](https://github.com/stoe/action-reporting-cli/commit/5f089c8c06369392d1843f169b335792713946c3) as opposed to setting it individually for each save csv, json, and markdown functions, but without refactoring the code I didn't see anywhere obvious since the workflow API returns empty and thus this [line never gets hit](https://github.com/stoe/action-reporting-cli/blob/5f089c8c06369392d1843f169b335792713946c3/utils/reporting.js#L316).

I agree, but your changes look great here.

**Comment by stoe** [comment]
I have deleted the scorecard.
Was just an experiment. Although I want to do this (some day) I don't have the bandwidth to address everything right now.

**Review by stoe — APPROVED** [review]

**Comment by joshjohanning** [comment]
🙇 thanks for the review and merge @stoe! 🎉

**Pull request merged**
